[package]
name = "typedb-go-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "typedb_go_ffi"
crate-type = ["staticlib"]

[dependencies]
typedb-driver = { version = "3.8.0", features = ["sync"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
serde_json = "1"
rmp-serde = "1"
